"""Stub file for custom_components/reflex_ohif_viewer/dicom_viewer.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal

import reflex as rx
from reflex.components.component import NoSSRComponent
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

__all__ = [
    "DicomViewer",
    "clear_measurements",
    "dicom_viewer",
    "flip",
    "jump_to_slice",
    "play_cine",
    "reset_camera",
    "reset_properties",
    "rotate",
    "scroll",
    "set_colormap",
    "set_tool",
    "set_window",
    "set_window_preset",
    "set_zoom",
    "stop_cine",
    "viewer_call",
    "window_preset_range",
]
ViewerMode = Literal["stack", "volume", "volume3d"]
Orientation = Literal["axial", "sagittal", "coronal", "acquisition"]

class DicomViewer(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        image_ids: Var[list[str]] | list[str] | None = None,
        wado_rs_root: Var[str] | str | None = None,
        study_instance_uid: Var[str] | str | None = None,
        series_instance_uid: Var[str] | str | None = None,
        sop_instance_uid: Var[str] | str | None = None,
        headers: Var[dict[str, str]] | dict[str, str] | None = None,
        viewport_id: Var[str] | str | None = None,
        rendering_engine_id: Var[str] | str | None = None,
        tool_group_id: Var[str] | str | None = None,
        volume_id: Var[str] | str | None = None,
        mode: Var[str] | str | None = None,
        orientation: Var[str] | str | None = None,
        background: Var[list[float]] | list[float] | None = None,
        initial_image_index: Var[int] | int | None = None,
        voi_range: Var[dict[str, float]] | dict[str, float] | None = None,
        window_width: Var[float] | float | None = None,
        window_center: Var[float] | float | None = None,
        invert: Var[bool] | bool | None = None,
        colormap: Var[str] | str | None = None,
        preset: Var[str] | str | None = None,
        slab_thickness: Var[float] | float | None = None,
        tools: Var[list[str]] | list[str] | None = None,
        active_tool: Var[str] | str | None = None,
        max_web_workers: Var[int] | int | None = None,
        wasm_base_path: Var[str] | str | None = None,
        cine: Var[bool] | bool | None = None,
        cine_frames_per_second: Var[int] | int | None = None,
        cine_loop: Var[bool] | bool | None = None,
        show_overlay: Var[bool] | bool | None = None,
        show_loading_indicator: Var[bool] | bool | None = None,
        overlay_color: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_annotation_added: EventType[Any] | None = None,
        on_annotation_modified: EventType[Any] | None = None,
        on_annotation_removed: EventType[Any] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_error: EventType[Any] | None = None,
        on_focus: EventType[()] | None = None,
        on_load_progress: EventType[Any] | None = None,
        on_measurements_change: EventType[Any] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_slice_change: EventType[Any] | None = None,
        on_unmount: EventType[()] | None = None,
        on_viewer_ready: EventType[Any] | None = None,
        on_voi_change: EventType[Any] | None = None,
        **props,
    ) -> DicomViewer:
        """Create the component after validating tool names.

        Args:
            *children: Ignored; the viewport manages its own DOM children.
            image_ids: Explicit Cornerstone imageIds (``wadors:`` or ``wadouri:``). When set, the DICOMweb props below are ignored. See :meth:`~reflex_ohif_viewer.dicomweb.DicomWebClient.image_ids`.
            wado_rs_root: WADO-RS root URL of the DICOMweb server.
            study_instance_uid: Study to load.
            series_instance_uid: Series to load.
            sop_instance_uid: Restrict the series to a single instance.
            headers: Extra request headers for the DICOMweb server, typically ``{"Authorization": "Bearer ..."}``. Applied to metadata *and* frame requests for every imageId under ``wado_rs_root``.
            viewport_id: Unique id for this viewport. Also the key under which the imperative API is registered, so pass it to :func:`viewer_call` and friends.
            rendering_engine_id: Rendering engine id. Viewports sharing an engine share a WebGL context, which is usually what you want on one page.
            tool_group_id: Tool group id. Defaults to ``f"{viewport_id}-tools"``. Share it across viewports for linked tools such as ``Crosshairs``.
            volume_id: Volume id, for ``mode="volume"``. Share it across viewports so the volume is decoded once and reused (the MPR pattern).
            mode: ``stack`` (2D frame-by-frame), ``volume`` (reformatted MPR plane) or ``volume3d`` (volume rendering).
            orientation: Reformat plane for ``mode="volume"``.
            background: Viewport background as ``[r, g, b]`` from 0 to 1.
            initial_image_index: Frame to open on. ``-1`` opens the middle of the stack.
            voi_range: Explicit VOI range, ``{"lower": ..., "upper": ...}``. Takes precedence over ``window_width`` / ``window_center``.
            window_width: Window width. Ignored when ``0``.
            window_center: Window center.
            invert: Invert the grayscale ramp.
            colormap: Colormap name, e.g. ``"Inferno (matplotlib)"``. Empty means grayscale.
            preset: Volume-rendering preset for ``mode="volume3d"``, e.g. ``"CT-Bone"``.
            slab_thickness: Slab thickness in millimetres for ``mode="volume"``.
            tools: Tools to register in the tool group. Empty uses :data:`~reflex_ohif_viewer.constants.DEFAULT_TOOLS`.
            active_tool: The tool bound to the primary (left) mouse button. Right-drag is always zoom, middle-drag and Ctrl+drag are pan, the wheel and Alt+drag scroll.
            max_web_workers: Frame-decode worker count. ``0`` uses half the hardware concurrency. Values above 3 are known to misbehave on some Windows hosts.
            wasm_base_path: Directory serving the codec ``.wasm`` files, e.g. ``"/cs-wasm/"``. Set this if frame decoding fails with ``WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f`` — that error means the bundler served ``index.html`` instead of the codec. See :class:`~reflex_ohif_viewer.plugin.CornerstonePlugin`, which copies them and sets this for you.
            cine: Auto-play the stack as a cine loop.
            cine_frames_per_second: Cine frame rate.
            cine_loop: Loop the cine playback.
            show_overlay: Draw the four-corner DICOM overlay (patient, study, series, W/L, zoom).
            show_loading_indicator: Show the built-in loading indicator.
            overlay_color: Overlay text colour.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_viewer_ready: Fired once the first image is displayed. Receives a dict with ``viewportId``, ``toolGroupId``, ``numImages``, ``index``, ``mode`` and the patient/study/series strings read from the DICOM metadata.
            on_slice_change: Fired on every frame change. Receives ``{"index": int, "total": int}``.
            on_voi_change: Fired when window/level changes. Receives ``{"windowWidth": float, "windowCenter": float}``.
            on_measurements_change: Fired whenever the annotation set changes. Receives the full list of measurements, each ``{"uid", "toolName", "label", "stats", ...}``.
            on_annotation_added: Fired when an annotation is completed.
            on_annotation_modified: Fired when an annotation is edited.
            on_annotation_removed: Fired when an annotation is deleted.
            on_load_progress: Fired as frames arrive. Receives ``{"loaded": int, "total": int}``. Chatty on large series — only wire it up if you show a progress bar.
            on_error: Fired when setup or loading fails. Receives the error message.
            **props: Component props.

        Returns:
            The configured component.

        Raises:
            ValueError: If ``tools`` or ``active_tool`` names a tool this
                component cannot register. Catching the typo here beats a
                silent console warning at runtime.

        """
        ...

dicom_viewer = DicomViewer.create

def viewer_call(viewport_id: str, method: str, *args: Any) -> rx.event.EventSpec: ...
def set_tool(viewport_id: str, tool: str) -> rx.event.EventSpec: ...
def reset_camera(viewport_id: str) -> rx.event.EventSpec: ...
def reset_properties(viewport_id: str) -> rx.event.EventSpec: ...
def jump_to_slice(viewport_id: str, index: int) -> rx.event.EventSpec: ...
def scroll(viewport_id: str, delta: int = 1) -> rx.event.EventSpec: ...
def set_window(viewport_id: str, width: float, center: float) -> rx.event.EventSpec: ...
def window_preset_range(preset: str) -> tuple[float, float]: ...
def set_window_preset(viewport_id: str, preset: str) -> rx.event.EventSpec: ...
def set_colormap(viewport_id: str, colormap: str) -> rx.event.EventSpec: ...
def set_zoom(viewport_id: str, zoom: float) -> rx.event.EventSpec: ...
def rotate(viewport_id: str, degrees: float) -> rx.event.EventSpec: ...
def flip(
    viewport_id: str, horizontal: bool = False, vertical: bool = False
) -> rx.event.EventSpec: ...
def play_cine(
    viewport_id: str, frames_per_second: int = 24, loop: bool = True
) -> rx.event.EventSpec: ...
def stop_cine(viewport_id: str) -> rx.event.EventSpec: ...
def clear_measurements(viewport_id: str) -> rx.event.EventSpec: ...
def remove_measurement(viewport_id: str, uid: str) -> rx.event.EventSpec: ...

DEFAULT_TOOLBAR: tuple[str, ...]
