"""Stub file for custom_components/reflex_ohif_viewer/ohif_viewer.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any

import reflex as rx
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

__all__ = ["OhifViewer", "build_ohif_url", "ohif_viewer"]

def build_ohif_url(
    base_url: str,
    *,
    mode: str = "viewer",
    data_source: str = "",
    study_instance_uids: list[str] | str | None = None,
    series_instance_uids: list[str] | str | None = None,
    study_list: bool = False,
    config_url: str = "",
    debug: bool = False,
    extra_params: dict[str, Any] | None = None,
    **options: Any,
) -> str: ...

class OhifViewer(rx.Component):
    @classmethod
    def create(
        cls,
        *children,
        base_url: Var[str] | str | None = None,
        mode: Var[str] | str | None = None,
        data_source: Var[str] | str | None = None,
        study_list: Var[bool] | bool | None = None,
        study_instance_uids: Var[list[str]] | list[str] | None = None,
        series_instance_uids: Var[list[str]] | list[str] | None = None,
        initial_series_instance_uid: Var[str] | str | None = None,
        initial_sop_instance_uid: Var[str] | str | None = None,
        hanging_protocol_id: Var[str] | str | None = None,
        stage_id: Var[str] | str | None = None,
        token: Var[str] | str | None = None,
        config_url: Var[str] | str | None = None,
        customization: Var[str] | str | None = None,
        theme: Var[str] | str | None = None,
        debug: Var[bool] | bool | None = None,
        use_next_viewports: Var[bool] | bool | None = None,
        viewport_rendering: Var[str] | str | None = None,
        multimonitor: Var[str] | str | None = None,
        screen_number: Var[str] | str | None = None,
        extra_params: Var[dict[str, str]] | dict[str, str] | None = None,
        worklist_filters: Var[dict[str, str]] | dict[str, str] | None = None,
        title: Var[str] | str | None = None,
        allow: Var[str] | str | None = None,
        sandbox: Var[str] | str | None = None,
        referrer_policy: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        on_url_change: EventType[Any] | None = None,
        on_viewer_load: EventType[Any] | None = None,
        on_viewer_message: EventType[Any] | None = None,
        **props,
    ) -> OhifViewer:
        """Create the component, linking its frontend asset on first use.

        Args:
            *children: Ignored; the iframe has no Reflex children.
            base_url: Where the OHIF build is served from.
            mode: The mode route segment: ``viewer``, ``segmentation``, ``tmtv``, ``microscopy``, ``dynamic-volume``, ``usAnnotation``, ``basic``.
            data_source: The ``sourceName`` path segment. Empty uses the build's default.
            study_list: Open the study list instead of a viewer mode.
            study_instance_uids: Studies to load. Several entries load a current study plus priors.
            series_instance_uids: Hard filter: only these series are retrieved.
            initial_series_instance_uid: Soft: load the whole study but start on this series.
            initial_sop_instance_uid: Navigate to this instance on load.
            hanging_protocol_id: A registered hanging protocol id, e.g. ``mpr`` or ``@ohif/mnGrid``.
            stage_id: A stage within the hanging protocol.
            token: Bearer token for the data source. OHIF strips it from the URL after reading it, but it is still a credential in a URL — prefer OIDC or a same-origin proxy for anything sensitive.
            config_url: URL of a JSON config for ``?configUrl=``. Requires the target build to enable ``dangerouslyUseDynamicConfig``.
            customization: A customization bundle name, subject to the build's ``customizationUrlPrefixes`` allowlist.
            theme: Theme name, preserved across OHIF's own navigation.
            debug: Add ``?debug=true``.
            use_next_viewports: Opt into the Cornerstone "next" generic viewport API.
            viewport_rendering: ``cpu``, ``webgl``, ``auto`` or a backend id.
            multimonitor: Multi-monitor layout id, e.g. ``split`` or a registered custom layout.
            screen_number: Which screen of the ``multimonitor`` layout this frame shows.
            extra_params: Extra query parameters, merged last.
            worklist_filters: Study-list filters, used when ``study_list`` is true. Keys are OHIF's own: ``patientName``, ``mrn``, ``description``, ``accession``, ``modalities``, ``startDate``, ``endDate``, ``sortBy``, ``sortDirection``, ``pageNumber``, ``resultsPerPage``.
            title: ``title`` attribute of the iframe, for assistive technology.
            allow: ``allow`` attribute. Keep ``cross-origin-isolated`` if the OHIF build is served with COOP/COEP for SharedArrayBuffer progressive loading.
            sandbox: ``sandbox`` attribute. Empty means no sandbox attribute is emitted. OHIF needs at least ``allow-scripts allow-same-origin`` to run.
            referrer_policy: ``referrerpolicy`` attribute.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_viewer_load: Fired when the iframe finishes loading. Receives the URL.
            on_url_change: Fired when the computed URL changes. Receives the URL.
            on_viewer_message: Fired for ``postMessage`` messages from the frame, filtered by origin. OHIF sends none by default; this is for deployments that add their own OHIF extension or serve OHIF behind a same-origin shim.
            **props: Component props.

        Returns:
            The configured component.

        """
        ...

ohif_viewer = OhifViewer.create
